/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fisica;

import Calculadora.CalculadoraCaidaLibre;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class CaidaLibre extends javax.swing.JFrame {

    List<String> listaValorAbuscar = Arrays.asList("Velocidad Inicial (Vo)", "Velocidad Final (Vf)", "Altura (H)", "Tiempo (t)");
    private boolean isVelocidadInicial = false;
    private boolean isVelocidadFinal = false;
    private boolean isAltura = false;
    private boolean isTiempo = false;

    /**
     * Creates new form CaidaLibre
     */
    public CaidaLibre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cbValorSeleccionado = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tfVelocidadIncial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfVelocidadFinal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfGravedad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfAltura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfTiempo = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        cbValorSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValorSeleccionadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor a encontrar");

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Velocidad Inicial (Vo)");

        jLabel3.setText("Velocidad FInal (Vf)");

        jLabel4.setText("Gravedad (g)");

        tfGravedad.setEditable(false);
        tfGravedad.setText("9.8");

        jLabel5.setText("Altura (H)");

        jLabel6.setText("Tiempo (t)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfVelocidadFinal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTiempo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAltura, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfGravedad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 325, Short.MAX_VALUE))
                            .addComponent(tfVelocidadIncial))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jLabel1))
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbValorSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbValorSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfVelocidadIncial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(tfVelocidadFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfGravedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        for (String string : listaValorAbuscar) {
            cbValorSeleccionado.addItem(string);
        }
    }//GEN-LAST:event_formComponentShown

    private void cbValorSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValorSeleccionadoActionPerformed
        // TODO add your handling code here:
        tfVelocidadIncial.setEditable(true);
        tfVelocidadFinal.setEditable(true);
        tfAltura.setEditable(true);
        tfTiempo.setEditable(true);
        isVelocidadInicial = false;
        isVelocidadFinal = false;
        isAltura = false;
        isTiempo = false;
        if (cbValorSeleccionado.getSelectedItem().toString().equals("Velocidad Inicial (Vo)")) {
            tfVelocidadIncial.setEditable(false);
            isVelocidadInicial = true;
        } else if (cbValorSeleccionado.getSelectedItem().toString().equals("Velocidad Final (Vf)")) {
            tfVelocidadFinal.setEditable(false);
            isVelocidadFinal = true;
        } else if (cbValorSeleccionado.getSelectedItem().toString().equals("Altura (H)")) {
            tfAltura.setEditable(false);
            isAltura = true;
        } else if (cbValorSeleccionado.getSelectedItem().equals("Tiempo (t)")) {
            tfTiempo.setEditable(false);
            isTiempo = true;
        } else {
            JOptionPane.showMessageDialog(this, "Eliga una opcion valida");
        }
    }//GEN-LAST:event_cbValorSeleccionadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Double vo;
        Double vf;
        Double g = 9.8;
        Double h;
        Double t;

        CalculadoraCaidaLibre calculadora = new CalculadoraCaidaLibre();
        if (isVelocidadInicial) {
            vo = calculadora.calcularVelocidadInicial(tfVelocidadFinal.getText(), tfAltura.getText(), tfTiempo.getText());
            tfVelocidadIncial.setText(vo.toString());
        } else if (isVelocidadFinal) {
            vf = calculadora.calcularVelocidadFinal(tfVelocidadIncial.getText(), tfAltura.getText(), tfTiempo.getText());
        } else if (isAltura) {
            h = calculadora.calcularAltura(tfVelocidadIncial.getText(), tfVelocidadFinal.getText(), tfTiempo.getText());
        } else if (isTiempo) {
            t = calculadora.calcularTiempo(tfVelocidadIncial.getText(), tfVelocidadFinal.getText(), tfAltura.getText());
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbValorSeleccionado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfGravedad;
    private javax.swing.JTextField tfTiempo;
    private javax.swing.JTextField tfVelocidadFinal;
    private javax.swing.JTextField tfVelocidadIncial;
    // End of variables declaration//GEN-END:variables
}
